version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # poetry
  - package-ecosystem: "pip"
    directory: "/"
    groups:
        prod-deps:
          dependency-type: "production"
        dev-deps:
          dependency-type: "development"
    schedule:
      interval: "daily"
  # poetry LTS
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "release/v0.9"
    allow:
      - dependency-type: "production"
    groups:
        prod-deps:
          dependency-type: "production"
        dev-deps:
          dependency-type: "development"
