# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.
- name: breaking
  description: Breaking Changes
  color: bfd4f2
- name: enhancement
  description: New feature or request
  color: a2eeef
- name: bug
  description: Something isn't working
  color: d73a4a
- name: performance
  description: Performance
  color: "016175"
- name: refactoring
  description: Refactoring
  color: ef67c4
- name: removal
  description: Removals and Deprecations
  color: 9ae7ea
- name: testing
  description: Testing
  color: b1fc6f
- name: style
  description: Style
  color: c120e5
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: ci
  description: Continuous Integration
  color: 4a97d6
- name: build
  description: Build System and Dependencies
  color: bfdadc
- name: dependencies
  description: Pull requests that update a dependency file
  color: 0366d6
- name: skip changelog
  description: Pull requests that do not need to be added in release note
  color: ffffff
# Extra labels for some PRs or issues
- name: github actions
  description: Pull requests that update Github_actions code
  color: "000000"
- name: good first issue
  description: Good for newcomers
  color: 7057ff
- name: wip
  description: Work in progress
  color: c4c5fc
- name: help wanted
  description: Extra attention is needed
  color: 008672
- name: question
  description: Further information is requested
  color: d876e3
- name: wontfix
  description: This will not be worked on
  color: ffffff
