version: 2

jobs:
  py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo make install
      - run: make all
      - run: sudo pip install codecov
      - run: codecov --token=556fb2ac-7fe9-4798-9d58-ad3f22be4aca
  py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo make install
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - py36
      - py37
